import { q, type Reading } from "./types";
type Draft = Omit<Reading, "version" | "words" | "skills" | "modes">;
export const longReadings: Draft[] = [
  {
    id: "r35",
    title: "Bir kütüphanenin ikinci hayatı",
    genre: "Anlatı",
    level: 2,
    complexity:
      "Uzun olay örgüsü, değişen bakış açıları ve parçalar arası ilişki.",
    role: "practice",
    paragraphs: [
      `Eski belediye binasının giriş katındaki kütüphane, taşınma kararı çıktığında bir süreliğine kapandı. Kitaplar kutulara kondu, rafların üzerine numaralar yazıldı. Binayı yıllardır kullananlar bu kapanışı yalnızca bir adres değişikliği olarak görüyordu. Kütüphanede çalışan Alev ise yeni mekânı hazırlarken eski alışkanlıkların ne kadarının taşınacağını merak ediyordu. Küçük bir deftere, son açık haftada gördüğü kullanımları yazmaya başladı. Kimin hangi kitabı aldığıyla değil, insanlar içeri girdikten sonra nasıl bir yol izlediğiyle ilgileniyordu. Bazıları doğrudan gazetelere gidiyor, bazıları danışmanın önünde durup konuşuyor, bazıları da okumak için değil, sessiz bir yerde düşünmek için köşedeki masaya oturuyordu. Bu hareketlerin hiçbiri taşınma listesindeki eşya sayılarında görünmüyordu.`,
      `Yeni bina daha genişti, fakat giriş kapısıyla raflar arasındaki mesafe uzundu. Mimarın ilk çiziminde danışma masası arka duvara yerleştirilmişti. Böylece giriş ferah kalacak, raflar kesintisiz görünecekti. Alev çizimin güzelliğine itiraz etmedi. Yalnızca eski kütüphaneye ilk kez gelen birinin genellikle önce bir yüz aradığını anlattı. Kitapların nerede olduğunu bilmeyen ziyaretçi, hangi yöne yürüyeceğini de bilemeyebilirdi. Bu gözlem üzerine masayı girişe taşımak yerine, kapıdan görünecek bir açıya çevirdiler. Alev için önemli olan mobilyanın belirli bir yerde durması değil, soru sorulabilecek kişinin kolay fark edilmesiydi. Aynı işlevin başka bir düzenle korunabileceğini görmek, taşınmaya bakışını biraz değiştirdi.`,
      `Taşınmadan önce mahallelilerle yapılan buluşmada en çok eski köşe masası konuşuldu. Masanın yüzeyi çizikti ve ayaklarından biri sallanıyordu. Yeni mobilyalar arasında ona yer ayrılmamıştı. Emekli bir öğretmen masada yıllarca sınav kâğıdı okuduğunu söyledi. Üniversiteye hazırlanan bir genç ise pencere önündeki ışığı sevdiğini anlattı. İki kişi aynı masayı anıyor, fakat farklı özelliklerini önemsiyordu. Alev defterine “masa” yazıp altına “süreklilik” ve “ışık” sözcüklerini ekledi. Tartışma, eski bir nesneyi korumakla yenisini almak arasında sıkışmış görünüyordu. Oysa bir yandan tanıdık bir yer duygusu, öte yandan rahat çalışma koşulu isteniyordu. Bu iki isteğin aynı çözümde buluşması mümkün olabilirdi.`,
      `Ekip masayı onarıp yeni binanın ışık alan bölümüne yerleştirmeye karar verdi. Yanına farklı yükseklikte iki yeni masa daha eklendi. Böylece eski masaya oturamayan biri de benzer aydınlıkta yer bulacaktı. Masanın üzerine geçmişini anlatan uzun bir yazı konmadı; küçük bir levhada yalnızca eski binadan geldiği belirtildi. Alev, nesnenin hikâyesinin kullanımı bastırmasını istemiyordu. Bir masa müzeye kaldırılmış gibi korunursa ona duyulan bağ da başka bir şeye dönüşebilirdi. İlk gün bir öğrenci çizik yüzeye defterini açtığında, onarımın amacına ulaştığını düşündü. Yine de bu düşüncesini genel başarı diye kaydetmedi; tek bir güzel an, bütün düzenin nasıl işleyeceğini söylemiyordu.`,
      `Açılıştan sonraki haftalarda beklenmedik bir sorun çıktı. Çocuk bölümüyle sessiz çalışma alanı birbirinden uzaktı, ama aradaki koridor sesi taşıyordu. Rafları duvar gibi dizmek önerildi. Alev önce hangi saatlerde sorun yaşandığını not etti. Çocuk etkinlikleri her gün yapılmıyor, gürültü çoğunlukla etkinlik bitimindeki bekleme sırasında yükseliyordu. Aileler kapıya yakın bir yerde toplanıyor ve çocuklar dar koridorda koşuyordu. Sorun yalnızca sesin kendisi değil, beklemek için uygun bir yerin olmamasıydı. Girişteki kullanılmayan bölüm birkaç oturakla düzenlendi; etkinlik sonunda ailelerin orada buluşması istendi. Sessizlik tamamen sağlanmadı, fakat çalışma alanındaki ani bölünmeler azaldı. Rafları yeniden taşımaya gerek kalmamıştı.`,
      `Bir başka konu da kütüphanenin başarı ölçüsüydü. Açılış haftasında gelen kişi sayısı çok yüksekti. Yerel bir duyuru bu sayıyı yeni binanın başarısı olarak paylaştı. Alev sayının yanlış olmadığını, ancak neyi gösterdiğinin sınırlı olduğunu söyledi. Bazı ziyaretçiler yalnızca binayı gezmişti. Bunun kötü bir yanı yoktu; yine de düzenli çalışma, kitap bulma ve uzun süreli kullanım başka gözlemler gerektiriyordu. Ekip aylık çizelgeye birkaç ayrı satır ekledi: ilk kez gelenler, aradığı kaynağı bulmakta yardım isteyenler ve çalışma alanındaki doluluk saatleri. Bu bilgiler kimseye bir değer puanı vermek için tutulmadı. Nerede daha çok desteğe ihtiyaç duyulduğunu anlamaya yarayacaktı.`,
      `İkinci ay Alev eski defterini yeniden açtı. Gazete okuyanların yeni binada başka bir köşe seçtiğini gördü. Eski yerde pencere yanında oturanlar, burada girişe yakın küçük masaları tercih ediyordu. Çünkü gazeteyi kısa süreliğine okuyup çıkanlar için kapıya yakınlık daha önemliydi. Bu değişiklik ona eski düzeni aynen kopyalamanın süreklilik olmadığını düşündürdü. İnsanların amaçları korunurken yolları değişebilirdi. Defterine bu kez nesneleri değil soruları yazdı: İnsan ne yapmak istiyor? Nerede duraksıyor? Yardımı nasıl buluyor? Bu soruların yanıtı tek bir çizimde kalmıyor, kullanım sürdükçe yeniden ortaya çıkıyordu. Yeni binanın genişliği ancak bu küçük kararlarla gerçek bir imkâna dönüşüyordu.`,
      `Kütüphane birkaç ay sonra günlük hayatın doğal parçalarından biri oldu. Eski köşe masası hâlâ doluydu; yeni masalar da öyle. Alev defteri kapatmadı, fakat her gün uzun uzun not tutmayı bıraktı. Belirli aralıklarla aynı sorulara dönmek yeterliydi. Taşınma listesindeki bütün kutuların açılması bir işin bittiğini gösteriyordu; kütüphanenin insanlara uygun hâle gelmesi ise başka bir süreçti. Bu süreçte her sorun büyük bir yeniden tasarım gerektirmiyor, her güzel gün de kalıcı başarı sayılmıyordu. Alev en çok bunu öğrenmişti. Bir yerin ikinci hayatı, eski eşyaların yeni duvarlar arasında durmasıyla değil, insanların tanıdık amaçlarına yeni koşullarda yer bulmasıyla başlıyordu. Binanın kapısındaki adres değişmişti; asıl değişim içeride sorulan sorulardaydı.`,
    ],
    questions: [
      q(
        "Ana düşünce",
        "Kütüphanenin “ikinci hayatı” en çok neye bağlıdır?",
        [
          "Eski düzeni aynen kopyalamaya",
          "Daha çok ziyaretçiyi tek ölçüt saymaya",
          "İnsanların amaçlarını yeni koşullarda desteklemeye",
          "Bütün eski eşyaları sergilemeye",
        ],
        2,
        "Son paragraf eşyaların taşınması ile kullanıma uygun yaşamı ayırır.",
        7,
      ),
      q(
        "Açık bilgi",
        "Ses sorunu için ilk uygulanan çözüm neydi?",
        [
          "Rafları duvar gibi dizmek",
          "Bekleme alanı oluşturmak",
          "Çocuk etkinliğini kaldırmak",
          "Koridoru kapatmak",
        ],
        1,
        "Sorunun etkinlik sonu bekleme sırasında arttığı görülüp oturaklı alan düzenleniyor.",
        4,
      ),
      q(
        "İlişki",
        "Eski masayı farklı kişiler neden istiyordu?",
        [
          "Aynı maddi değeri önemsiyorlardı.",
          "Yeni bina küçüktü.",
          "Masada daha çok kitap vardı.",
          "Tanıdıklık ve ışık gibi farklı ihtiyaçları karşılıyordu.",
        ],
        3,
        "Öğretmen sürekliliği, genç aydınlığı anlatıyor.",
        2,
      ),
      q(
        "Çıkarım",
        "Gazete köşesinin değişmesi neyi gösterir?",
        [
          "İşlev korunurken fiziksel düzen değişebilir.",
          "Eski kullanıcılar geri gelmemiştir.",
          "Gazeteler artık okunmuyordur.",
          "Kapıya yakınlık herkes için en önemli şeydir.",
        ],
        0,
        "Kısa ziyaretler için kapı yakınlığı, eski pencere konumundan daha yararlı oluyor.",
        6,
      ),
      q(
        "Bağlam",
        "“Tek bir güzel an” neden genel başarı sayılmıyor?",
        [
          "Alev öğrenciyi tanımadığı için",
          "Uzun dönem kullanım hakkında yeterli gözlem sunmadığı için",
          "Masa yeni olmadığı için",
          "Açılışta kayıt tutulmadığı için",
        ],
        1,
        "Bir öğrencinin kullanımı, bütün düzeni ve zaman içindeki sonuçları temsil etmez.",
        3,
      ),
    ],
    summary:
      "Alev kütüphaneyi taşırken eşyalar yerine kullanım amaçlarını izler. Danışma, eski masa ve bekleme alanı küçük gözlemlerle düzenlenir. Başarı tek bir ziyaret sayısından değil, farklı ihtiyaçlara uygun kullanımdan okunur.",
    points: [
      "Eşya listeleri kullanım amaçlarını göstermiyordu.",
      "Eski masa farklı insanlar için farklı değerler taşıyordu.",
      "Gürültünün bir nedeni uygun bekleme alanının yokluğuydu.",
      "Ziyaret sayısı tek başına kullanım kalitesini kanıtlamıyordu.",
      "Süreklilik aynı düzeni kopyalamak değildi.",
    ],
    scan: {
      prompt: "Aileler için bekleme alanı hangi bölümde kuruldu?",
      answer: "Girişteki kullanılmayan bölümde",
      paragraph: 4,
    },
  },
  {
    id: "r36",
    title: "Yavaş yapılan bir harita",
    genre: "Anlatı",
    level: 2,
    complexity:
      "Birden fazla amaç, değişen model ve uzun süreli neden ilişkisi.",
    role: "practice",
    paragraphs: [
      `Beldeye yeni taşınan Eren, ilk hafta her yere telefonundaki haritayla gitti. Harita onu markete, duraklara ve belediye binasına ulaştırıyordu. Fakat bir ay sonra hâlâ çevresini tanımadığını hissediyordu. Sokak adlarını biliyor, sokakların birbirinden nasıl farklılaştığını anlatamıyordu. Bir gün işe giderken şarjı bitince aynı köşeden iki kez döndü. Aradığı yolun adını hatırladı, ama girişindeki küçük dükkânı tanımadı. Eve döndüğünde bir kâğıda yürüdüğü yolu çizdi. Çizim ölçeksizdi ve birçok boşluk içeriyordu. Buna rağmen ilk kez nereleri gerçekten hatırladığını, nerelerde yalnızca ekrandaki oku izlediğini görebilmişti. Boşluklar çizimin kusurundan çok kendi bilgisinin sınırlarını anlatıyordu.`,
      `Ertesi sabah yolun bir bölümünde telefonu cebinde tuttu. Kendine bütün kasabayı öğrenme görevi vermedi; yalnızca evden ilk meydana kadar üç dönüm noktasını seçti. Köşedeki mavi kapı, iki sokağın birleştiği çeşme ve kaldırımın daraldığı fırın önü. Akşam çizimine bu işaretleri ekledi. Sokakların açıları hâlâ doğru değildi, ancak aralarındaki sıra daha açıktı. Eren, haritanın görünüşüyle işe yararlılığının ayrı şeyler olduğunu fark etti. Güzel bir çizim yapmaya çalışsaydı, önce çizgilerin düzgünlüğüyle uğraşacaktı. Oysa şu anki sorusu başkaydı: Hangi işaretten sonra nereye dönüyorum? Kâğıt bu soruyu cevaplayabildiği ölçüde kullanışlıydı.`,
      `Bir hafta sonra komşusu İnci, çizime baktı ve en sevdiği yürüyüş yolunun hiç görünmediğini söyledi. Eren o yolun meydana çıkmadığını hatırlattı. İnci zaten meydana gitmek için yürümediğini, akşam biraz dolaşmak istediğini anlattı. Çınarların altından geçen yolun sonunda küçük bir bahçe vardı. Yol uzundu ama yokuşu daha azdı. İkisi aynı sokaklara bakıyor, farklı güzergâhlar görüyordu. Eren kâğıdın arkasına ikinci bir çizim yaptı. Bu kez hedefe en kısa sürede ulaşmak yerine yürüyüşün rahatlığını işaretledi. Tek haritada bütün bilgileri biriktirmek mümkün görünüyordu; fakat böyle yapınca hangi işaretin hangi amaç için önemli olduğu belirsizleşebilirdi.`,
      `Belde derneğinde bir gönüllü, yeni gelenler için basit bir harita hazırlanmasını önerince Eren iki çizimini götürdü. Toplantıda herkes eklenmesini istediği bir şey söyledi: eczane, oyun alanı, su içilebilen çeşme, merdivensiz geçiş, gölgeli oturma yeri. İlk taslak kısa sürede işaretlerle doldu. Küçük kâğıtta yazılar birbirine karışıyor, yollar zor seçiliyordu. Ekip bilgileri silmek konusunda anlaşamadı; her işaret birinin gerçek ihtiyacına karşılık geliyordu. Sonunda tek bir haritanın her soruyu yanıtlamasını beklemekten vazgeçtiler. Bir ana yön haritası ve onun yanında farklı amaçları gösteren kısa güzergâh sayfaları hazırlamaya karar verdiler. Bilgiler azalmıyor, farklı sorulara göre düzenleniyordu.`,
      `Harita hazırlandıktan sonra iki yeni ziyaretçiden onu kullanarak dernek binasına gelmeleri istendi. Bir ziyaretçi doğru sokağa girdi, fakat binanın kapısını geçti. Kâğıtta bina bir dikdörtgenle gösterilmişti; gerçek giriş yan taraftaydı. Diğeri çeşmeyi ararken kapatılmış bir musluğu fark etmedi, çünkü çizimde büyük bir havuz simgesi kullanılmıştı. Eren ilk anda ziyaretçilerin yeterince dikkatli bakmadığını düşündü. Sonra kendi çizimini savunmak yerine onların gördüklerini dinledi. Simgeler çizeni için açıktı, fakat ilk kez gören kişi başka bir nesne bekliyordu. Giriş işareti yana taşındı, çeşme simgesinin yanına kısa bir sözcük eklendi. Küçük değişiklikler, daha uzun bir açıklama toplantısından fazla işe yaradı.`,
      `Yaz yaklaşırken gölgeli yürüyüş sayfasında başka bir eksik ortaya çıktı. Sabah rahat olan yol, öğleden sonra güneşte kalıyordu. “Gölgeli” sözcüğü tek başına kesin bir özellik gibi görünmüş, günün saati atlanmıştı. Ekip sayfaya “sabah yürüyüşü” başlığını koydu. Bu ek, haritayı daha sınırlı ama daha doğru hâle getirdi. Eren artık bir bilginin yanına koşul yazmayı gereksiz ayrıntı saymıyordu. Koşul, bilginin ne zaman kullanılacağını gösteriyordu. Aynı nedenle geçici yol çalışmaları ana haritaya kalıcı biçimde basılmadı; dernek girişindeki değişebilir not alanında tutuldu. Sabit bilgilerle sık değişen bilgileri ayırmak, her küçük değişiklikte bütün haritayı yenileme yükünü de azaltıyordu.`,
      `Aylar sonra Eren'in telefonuna bakma ihtiyacı azalmıştı. Bunu kendi yön duygusunun olağanüstü gelişmesi olarak anlatmadı. Tanıdığı yolları, sık kullandığı işaretleri ve daha önce yaptığı hataları öğrenmişti. Bilmediği bir mahallede yine yardım alıyordu. Kâğıt harita da artık yalnızca kişisel bir çizim değildi; farklı insanların geri bildirimleriyle gelişmiş bir araçtı. Dernek, her yeni ziyaretçiden yorum istemeyi sürdürmedi. Belirli aralıklarla haritayı yeniden yürüyerek kontrol etmek ve belirgin bir sorun bildirildiğinde ilgili bölümü düzeltmek yeterliydi. Böylece araç, sürekli bakım isteyen ağır bir projeye dönüşmeden kullanışlı kalabiliyordu. En değerli notlar, insanların nerede durup hangi soruyu sorduğunu anlatan kısa cümlelerdi.`,
      `Eren ilk çizimini atmadı. Kâğıdın ortasındaki büyük boşluk hâlâ oradaydı. Yeni haritayla yan yana koyunca yalnızca daha çok sokak öğrendiğini görmüyordu. Bir şeyi temsil etmenin, o şeyin bütününü küçültüp sayfaya koymak olmadığını anlamıştı. Her çizim bir amaç seçiyor, bazı ilişkileri öne çıkarıyor ve bazılarını geride bırakıyordu. İyi bir harita bu seçimi saklamıyor, okuyucusuna ne için kullanılabileceğini belli ediyordu. Eren bir kitabın içindekilerine ya da bir toplantı özetine baktığında da aynı soruyu sormaya başladı: Bu düzen bana hangi yolu göstermek için yapılmış? Yavaş çizilen harita, sonunda yalnızca beldeyi değil, bilgiyle nasıl yön bulunacağını da düşünmesine yardım etmişti.`,
    ],
    questions: [
      q(
        "Ana düşünce",
        "Metnin bütününü en iyi hangi cümle özetler?",
        [
          "Her bilgi tek bir haritada bulunmalıdır.",
          "Haritalar yalnızca sokak adlarını göstermelidir.",
          "Telefon kullanmayan kişi daha iyi yön bulur.",
          "Bilgiyi temsil etmenin yararı, amaç ve kullanım koşuluna bağlıdır.",
        ],
        3,
        "Son paragraf haritayı diğer bilgi düzenlerine bağlayarak amaç seçimini vurgular.",
        7,
      ),
      q(
        "Açık bilgi",
        "Binayı geçen ziyaretçi için hangi değişiklik yapıldı?",
        [
          "Giriş işareti yan tarafa taşındı.",
          "Sokak adı kaldırıldı.",
          "Bina daha büyük çizildi.",
          "Harita tamamen iptal edildi.",
        ],
        0,
        "Gerçek giriş yanda olduğu için işaretin yeri düzeltildi.",
        4,
      ),
      q(
        "İlişki",
        "Neden ayrı güzergâh sayfaları hazırlandı?",
        [
          "İhtiyaçların çoğu önemsiz olduğu için",
          "Bütün işaretler tek sayfada amaçları ve yolları belirsizleştirdiği için",
          "Ziyaretçiler yürümeyi sevmediği için",
          "Ana harita hiç okunmadığı için",
        ],
        1,
        "İşaret yoğunluğu farklı gerçek ihtiyaçları tek görünümde karıştırıyordu.",
        3,
      ),
      q(
        "Çıkarım",
        "“Sabah yürüyüşü” başlığının eklenmesi ne sağlar?",
        [
          "Yolun her zaman gölgeli olmasını",
          "Yolun kısalmasını",
          "Bilginin geçerli olduğu koşulun açıklanmasını",
          "Bütün günlerin aynı olmasını",
        ],
        2,
        "Gölge saatle değiştiği için kapsam daraltılıyor.",
        5,
      ),
      q(
        "Bağlam",
        "İlk çizimdeki boşluk neyi temsil eder?",
        [
          "Beldede bina olmadığını",
          "Kâğıdın küçük olduğunu",
          "Yolun kapandığını",
          "Eren’in bilgisinin henüz tamamlanmayan yerlerini",
        ],
        3,
        "İlk paragraf boşluğu çizim kusurundan çok bilgi sınırı olarak yorumlar.",
        0,
      ),
    ],
    summary:
      "Eren kendi yolunu hatırlamak için çizdiği haritayı, farklı kullanıcı amaçlarıyla yeniden düzenler. Denemeler simgeleri ve koşulları düzeltir. Harita deneyimi, bilgiyi amaca göre seçme ve sınırlarını açık etme anlayışına dönüşür.",
    points: [
      "İlk çizim neyin hatırlandığını gösterdi.",
      "Farklı amaçlar farklı güzergâh bilgisi istedi.",
      "İlk kullanıcı deneyimi simgelerin belirsizliğini ortaya çıkardı.",
      "Gölgeli olma bilgisine saat koşulu eklendi.",
      "Temsil her şeyi değil, amaca uygun ilişkileri seçer.",
    ],
    scan: {
      prompt: "Geçici yol çalışmaları nerede tutuldu?",
      answer: "Dernek girişindeki değişebilir not alanında",
      paragraph: 5,
    },
  },
  {
    id: "r37",
    title: "Tamir masasının öbür tarafı",
    genre: "Tartışma",
    level: 3,
    complexity: "Bir savın kapsamı, karşı örnekler ve farklı değer ölçütleri.",
    role: "practice",
    paragraphs: [
      `Bir eşya bozulduğunda ilk soru genellikle “Tamir olur mu?” olur. Bu soru gereklidir, ama kararın tamamını kapsamaz. Ne kadar zaman gerektiği, parçanın bulunup bulunmadığı, eşyanın güvenle kullanılabilir olup olmayacağı ve kullanıcı için taşıdığı anlam da önemlidir. Mahallede ayda bir kurulan tamir masasına gelen nesneler bunu açıkça gösteriyordu. Aynı türden iki sandalye bile aynı karara götürmüyordu. Biri kolayca onarılıp kullanılabilirken diğerinin gövdesi yük taşımaya uygun görünmüyordu. Gönüllüler zamanla her başvuruya hemen bir sonuç sözü vermek yerine, önce sorunu anlamayı öğrenmişti. Bu yaklaşım daha az gösterişliydi; yine de masaya gelen insanların ne bekleyeceğini açıklaştırıyordu.`,
      `İlk buluşmalarda tamamlanan onarım sayısı duvara yazılıyordu. Sayı arttıkça gönüllüler seviniyordu. Ancak bir gün yaşlı bir ziyaretçi annesinden kalan küçük bir ahşap kutuyu getirdi. Kutu kapanıyor, menteşesi çalışıyor, yalnızca kapağında bir çatlak bulunuyordu. Ziyaretçi çatlağın tamamen silinmesini istemedi. Kutu açılıp kapanırken büyümemesini istiyordu; izin kendisi anının bir parçasıydı. Gönüllü Deniz önce yüzeyi zımparalamayı önerdi, sonra isteği yeniden dinledi. Burada başarı, nesneyi yeni gibi göstermek değildi. Kullanıcının korumak istediği şey ile değiştirmek istediği şey farklıydı. Tamir masası yalnızca teknik bir sorun çözmüyor, bu ayrımı da anlamak zorunda kalıyordu.`,
      `Başka bir ziyaretçi, ucuz bir masa lambasını tamir ettirmek için uzun süre bekledi. Bir gönüllü yenisini almanın daha kolay olabileceğini söyledi. Ziyaretçi lambanın maddi değerini biliyordu; asıl öğrenmek istediği, kablonun hangi noktada zarar gördüğünün nasıl anlaşılacağıydı. Güvenli olmayan bir müdahaleyi kendi başına yapması teşvik edilmedi. Bunun yerine sorun belirleme süreci kendisine açıklandı ve uygun uzman desteğine yönlendirildi. Lamba o gün masadan çalışır durumda ayrılmadı. Yalnızca onarım sayısına bakılsaydı bu karşılaşma sıfır katkı gibi görünecekti. Oysa kişi artık neyin bilinmediğini ve sonraki adımın ne olması gerektiğini daha açık biliyordu. Bu, tamamlanmış onarımdan farklı bir sonuçtu.`,
      `Bu örnekler her nesnenin mutlaka korunması gerektiğini göstermez. Bazen onarım için gereken zaman, alan ya da kaynak başka bir işten vazgeçmek anlamına gelir. Güvenli biçimde kullanılmayacak bir eşyanın sırf hatırası var diye çalışır durumda tutulması da doğru olmayabilir. Tamir masasındaki ekip bu nedenle “saklamak”, “kullanmak” ve “başka biçimde değerlendirmek” seçeneklerini ayırdı. Kullanılamayan bir sandalyenin sırt bölümü duvara asılan bir hatırlatıcıya dönüşebilirdi; fakat bu, sandalyenin onarıldığı diye kaydedilmezdi. Adlandırma önem taşıyordu. Farklı sonuçları aynı başarı sözcüğünün içine koymak, hem yapılan işi olduğundan büyük gösteriyor hem de gerçek çeşitliliğini gizliyordu. Açık sözcükler daha sakin kararlar alınmasını sağlıyordu.`,
      `Bir süre sonra gönüllüler küçük bir kabul formu hazırladı. Formda marka ya da satın alma fiyatından önce “Bu eşyayla yeniden ne yapabilmek istiyorsunuz?” sorusu vardı. Ardından bilinen sorunlar ve daha önce denenmiş işlemler soruluyordu. Bu sıralama bazı görüşmeleri kısalttı. Bir ziyaretçi çekmecenin rengini değiştirmek istediğini sanıyor, aslında karanlık odada içindekileri bulamamaktan yakınıyordu. Başka bir ışık kaynağı veya daha açık bir iç düzen, boyamadan daha uygun olabilirdi. Form kimsenin isteğini geçersiz saymak için kullanılmadı. Söylenen çözümün arkasındaki ihtiyacı anlamaya yarıyordu. İnsanların ilk önerisi çoğu zaman değerlidir, fakat her zaman tek mümkün yol değildir.`,
      `Ekip içinde bu yaklaşımı fazla konuşma olarak görenler de vardı. Onlara göre masa tamir yapmak için kurulmuştu; her nesnenin hikâyesini dinlemek işlerin yetişmesini engelliyordu. İtiraz bütünüyle haksız değildi. Uzun sohbetler sırasında diğer ziyaretçiler bekliyordu. Bunun üzerine ilk görüşme için kısa bir sıra oluşturuldu: amaç, belirti, güvenli sonraki adım. Ayrıntılı hikâye ancak kararı etkiliyorsa konuşulacaktı. Böylece ihtiyaç anlamak ile sınırsız görüşme yapmak birbirinden ayrıldı. İyi bir ilkeyi sürdürmek, onun her uygulamasını sınırsız büyütmek demek değildi. Gönüllüler de kendi zamanlarının ortak bir kaynak olduğunu ve dikkatli kullanılmasının hizmetin bir parçası sayıldığını fark ettiler.`,
      `Yıl sonunda yapılan değerlendirmede tamamlanan onarımlar yine sayıldı. Bu veri atılmadı; sadece tek başına bırakılmadı. Yanına sorunu açıklığa kavuşan nesneler, güvenlik nedeniyle yönlendirilen işler ve başka kullanıma dönüştürülen parçalar eklendi. Bazı kişiler birden fazla başlıkta yer alabilirdi; bu nedenle başlıklar toplanıp tek bir büyük başarı sayısı üretilmedi. Gönüllüler hangi işlerde parça beklediğini, hangi açıklamaların sık gerektiğini ve masaya hangi araçların eksik geldiğini bu ayrımlarla daha iyi gördü. Kayıt, başkalarına etkileyici görünmekten çok sonraki buluşmayı hazırlamaya yarıyordu. Değerlendirmenin işe yararlılığı, sayının büyüklüğünde değil, hangi kararı değiştirebildiğinde ortaya çıkıyordu.`,
      `Tamir masası bize eşyalar kadar kararlarımız hakkında da bir şey söyler. Bir işi iyi yapmak için önce neyi iyi sonuç saydığımızı bilmemiz gerekir. Kullanıcı nesnenin eski görünüşünü korumak istiyorsa kusursuz yeni yüzey yanlış hedef olabilir. Sadece çalışır ürün sayarsak öğrenilen doğru sonraki adımı göremeyebiliriz. Öte yandan bütün görüşmeleri onarım başarısı sayarsak olmayan bir sonucu varmış gibi gösteririz. Bu iki hata arasında dikkatli bir dil ve açık ölçütler bulunur. Masanın öbür tarafındaki insanı anlamak teknik bilgiyi gereksiz kılmaz; o bilginin hangi soruya uygulanacağını seçtirir. Bazen en iyi sonuç tamir edilmiş bir kutudur, bazen güvenli bir yönlendirme, bazen de artık neyin yapılmaması gerektiğini bilmektir.`,
    ],
    questions: [
      q(
        "Ana düşünce",
        "Yazının temel savı hangisidir?",
        [
          "Her nesne ne olursa olsun korunmalıdır.",
          "Tamir kararı ihtiyacı, güvenliği ve farklı sonuç türlerini birlikte düşünmelidir.",
          "Tamir sayısını tutmak gereksizdir.",
          "Uzun görüşmeler daima daha iyi hizmet sağlar.",
        ],
        1,
        "Son paragraf ihtiyaç, teknik bilgi ve ayrı sonuçları birlikte kurar.",
        7,
      ),
      q(
        "Açık bilgi",
        "Ahşap kutuyu getiren kişi ne istiyordu?",
        [
          "Bütün izlerin silinmesini",
          "Renginin değişmesini",
          "Çatlağın büyümemesini",
          "Menteşenin kaldırılmasını",
        ],
        2,
        "Kullanıcı anının parçası olan izi korumak istiyor.",
        1,
      ),
      q(
        "İlişki",
        "Amaç sorusu neden formun başına alındı?",
        [
          "Önerilen çözümün arkasındaki ihtiyacı anlamak için",
          "Ürün fiyatını gizlemek için",
          "Sohbetleri sınırsız uzatmak için",
          "Teknik soruları kaldırmak için",
        ],
        0,
        "Çekmece örneği, söylenen çözümün tek yol olmadığını gösteriyor.",
        4,
      ),
      q(
        "Çıkarım",
        "Farklı sonuç başlıkları neden toplanmadı?",
        [
          "Kayıtlar kaybolduğu için",
          "Onarımlar başarısız olduğu için",
          "Ekip saymayı bilmediği için",
          "Aynı kişi birden fazla başlıkta olabileceği için",
        ],
        3,
        "Toplama, ayrı sonuçları ve tekrar sayımı tek rakamda karıştırabilirdi.",
        6,
      ),
      q(
        "Bağlam",
        "“İlkeyi sınırsız büyütmek” hangi örneğe karşılık gelir?",
        [
          "Amaç sorusunu sormaya",
          "İhtiyacı anlamayı sınırsız sohbet zorunluluğuna çevirmeye",
          "Güvenli yönlendirmeye",
          "Kısa görüşme sırasına",
        ],
        1,
        "Zaman itirazıyla amaçlı dinleme ve sınırsız sohbet ayrılıyor.",
        5,
      ),
    ],
    summary:
      "Tamir masasının deneyimleri başarıyı yeni gibi görünüm veya onarım sayısına indirgememeyi öğretir. İhtiyaç, güvenlik ve kaynaklar birlikte değerlendirilir; farklı sonuçlar doğru adlarla kaydedilir.",
    points: [
      "Kutunun izi korunmak isteniyordu.",
      "Yönlendirme tamamlanmış onarımla aynı değildir.",
      "İlk çözüm önerisi ihtiyacın kendisi olmayabilir.",
      "Dinleme süresi de ortak kaynaktır.",
      "Sonuç türleri tek toplamda karıştırılmadı.",
    ],
    scan: {
      prompt: "Kısa görüşme sırasının üç başlığı nedir?",
      answer: "Amaç, belirti, güvenli sonraki adım",
      paragraph: 5,
    },
  },
  {
    id: "r38",
    title: "Bir bahçeyi okumak",
    genre: "Doğa",
    level: 2,
    complexity: "Zamana yayılan gözlem, olası nedenler ve bütüne dönüş.",
    role: "practice",
    paragraphs: [
      `Mina yeni evinin arkasındaki bahçeyi ilk gördüğünde boş bir alan saymıştı. Toprağın üzerinde birkaç ot, köşede eski bir saksı ve duvar boyunca dar bir taş şerit vardı. İçeri girer girmez nereye masa koyacağını düşündü. Bir hafta sonra aynı yere sabah erken çıktığında, akşam serin sandığı köşenin doğrudan güneş aldığını gördü. Masa için seçtiği yerin bütün gün aynı olmadığını fark etti. Bahçe yalnızca yerlerden değil, zaman içinde değişen koşullardan oluşuyordu. Mina hemen bir plan çizmek yerine birkaç gün farklı saatlerde dışarı çıkmaya karar verdi. Bu karar büyük bir doğa araştırması değildi; kendi kullanacağı alanı biraz daha doğru tanımak istiyordu.`,
      `İlk notları çok basitti: sabah kapı yanı aydınlık, öğlen duvar dibi gölgeli, akşam taş şerit sıcak. Notların yanına ne yapmak istediğini de yazdı. Kahvaltıda güneş hoşuna gidiyordu; uzun süre kitap okuyacağı yerde ise aynı ışık gözünü alabilirdi. Böylece “iyi köşe” diye tek bir yer aramaktan vazgeçti. Bir köşenin iyi olması kullanıma ve saate bağlıydı. Bu ayrım planı karmaşıklaştırmadı, tersine bazı kararları kolaylaştırdı. Ağır bir masa almak yerine kolay taşınan küçük bir masa seçti. Her gün bütün eşyaların yerini değiştirmek istemiyordu, ama gerektiğinde başka bir köşeye geçebilme olanağı ona yeterli görünüyordu.`,
      `Komşusu Tülay bahçeye bakıp köşedeki otların hemen temizlenmesini önerdi. Mina önce hepsini yolmayı düşündü. Sonra hangi alanı gerçekten kullanacağını belirlemeden bütün yüzeyi değiştirmek istemedi. Yürüyeceği dar yolu açtı, diğer yerleri bir süre bıraktı. Yağmurdan sonra temizlediği bölümde suyun daha uzun kaldığını fark etti. Bunun tek nedeninin otları kaldırmak olduğunu söyleyemezdi; yerin çukurluğu da etkili olabilirdi. Yine de gözlem, aceleyle büyük bir değişiklik yapmamak için yeterli bir neden sundu. Bir sonraki adımını seçmek için her şeyi kesin açıklaması gerekmiyordu. Belirsizliği kabul ederek küçük ve geri alınabilir bir düzenleme yapmak mümkündü.`,
      `Bahçede çalışırken en çok zorlandığı şey, gördüğü bir duruma hemen neden yakıştırmaktı. Bir sabah küçük saksıdaki bitkinin yaprakları sarkmıştı. Mina su az geldiğini düşündü ve elini toprağa değdirdi. Toprak nemliydi. Saksının öğleden sonra sıcak duvarın dibinde kaldığını hatırladı, fakat bu da kesin bir açıklama değildi. Bitkiyi daha dengeli ışık alan bir yere koyup gözlemlemeyi seçti. Burada amacı uzman gibi tanı koymak değil, alışkanlıkla aynı müdahaleyi tekrarlamaktan kaçınmaktı. Her belirtiye daha çok suyla karşılık vermek, tek bir çözümü bütün sorunlara uygulamak olacaktı. Kendi bilgisinin sınırını bilmek bahçeyle ilgilenmesini durdurmuyor, daha dikkatli yapıyordu.`,
      `Zamanla defterinde yalnızca sorunlar birikmeye başladı. Güneş fazlaydı, yol ıslaktı, sandalye sallanıyordu. Notları okuyunca bahçenin hiç iyi bir yanı yokmuş gibi görünüyordu. Oysa orada birçok rahat akşam geçirmişti. Sonraki sayfaya iyi işleyen durumları da yazdı: rüzgârlı havada duvar yanı sakindi, küçük masa kolay taşınıyordu, kapıya yakın bölüm kısa molalar için uygundu. Bu notlar sorunları yok saymak değildi. Değişiklik yaparken neyin korunması gerektiğini gösteriyordu. Yalnızca aksayan yerleri kaydetmek, bütün düzeni olduğundan kötü gösterebilir ve işe yarayan parçaların da gereksizce değiştirilmesine yol açabilirdi. Defter iki yönlü olunca kararlar daha dengeli hâle geldi.`,
      `Bir arkadaş buluşmasında bahçe ilk kez kalabalık kullanıldı. Mina iki kişi için rahat olan geçişin altı kişiyle daraldığını gördü. Masayı biraz kaydırdı, saksılardan birini duvarın yanına aldı. Ertesi gün bunları kalıcı değişiklik yapıp yapmaması gerektiğini düşündü. Kalabalık buluşmalar ayda bir olacaktı; günlük kullanımda eski düzen daha rahattı. Bu nedenle iki düzenin basit bir çizimini tuttu. Büyük bir sistem kurmadı, yalnızca hangi eşyanın nereye alınacağını hatırlayacak kadar işaret koydu. Ara sıra ortaya çıkan bir ihtiyacı her günün kuralına çevirmemek de bir tasarım kararıydı. Bahçenin hem gündelik sessizliğe hem seyrek buluşmalara yer açması, tek bir sabit biçimden daha yararlıydı.`,
      `Yaz sonunda Mina ilk fotoğrafla son hâli karşılaştırdı. Değişiklikler düşündüğünden küçüktü. Büyük bir düzenleme yaptırmamış, pahalı bir takım almamıştı. Fakat hangi saatte nereye oturacağını, yağmur sonrası hangi geçişi kullanacağını ve misafir geldiğinde neyi taşıyacağını biliyordu. Bir yabancı fotoğraflara bakıp çok az ilerleme olduğunu söyleyebilirdi. Mina için fark, görüntüden çok kullanımdaydı. Bu nedenle bahçeyi anlatırken yalnızca önce ve sonra fotoğraflarını göstermedi. İlk varsayımlarını, değişen kararlarını ve hâlâ bilmediği şeyleri de söyledi. Her köşenin neden öyle kaldığını bilmek, kusursuz görünen bir alan elde etmekten daha değerliydi. Bahçe artık boş değil, ilişkileri anlaşılmış bir yerdi.`,
      `Bir bahçeyi okumak, buradaki her şeyi adlandırmak ya da bütün nedenleri çözmek anlamına gelmiyordu. Mina için okumak, işaretlere dikkat etmek, ilk yorumunu sınamak ve kendi amacına uygun bir sonraki adımı seçmekti. Bazen yavaşlayıp izlemek, bazen küçük bir değişiklik yapıp sonucuna dönmek gerekiyordu. Tek bir kötü gün bütün düzenin başarısızlığı sayılmıyor; güzel bir akşam da her koşulda iyi işlediğini kanıtlamıyordu. Bu yaklaşım zamanla evin başka işlerine de taşındı. Bir alanı düzenlerken önce neyin eksik olduğuna değil, orada ne yapmak istediğine bakmaya başladı. Bahçenin en kalıcı ürünü yeni bir eşya değil, daha iyi sorular sorma alışkanlığı olmuştu.`,
    ],
    questions: [
      q(
        "Ana düşünce",
        "Metin bütün olarak neyi anlatıyor?",
        [
          "Bahçede bütün otların korunmasını",
          "Her sorun için aynı bakımın yapılmasını",
          "Gözlem ve amaçla küçük kararları geliştirmeyi",
          "En iyi bahçenin değişmeyen bahçe olduğunu",
        ],
        2,
        "Son paragraf gözlem, yorum ve amaca uygun adımı birleştirir.",
        7,
      ),
      q(
        "İlişki",
        "Mina neden iyi işleyen durumları da yazdı?",
        [
          "Defteri doldurmak için",
          "Değişiklikte korunacak parçaları görebilmek için",
          "Sorunları gizlemek için",
          "Arkadaşlarını ikna etmek için",
        ],
        1,
        "Sadece sorun kaydı tüm düzeni olduğundan kötü gösteriyordu.",
        4,
      ),
      q(
        "Açık bilgi",
        "Kalabalık kullanım için ne yaptı?",
        [
          "Bütün eşyaları attı.",
          "Buluşmaları iptal etti.",
          "Yeni bahçe aldı.",
          "İki düzeni hatırlatacak basit çizimler tuttu.",
        ],
        3,
        "Gündelik ve seyrek kalabalık kullanım ayrıldı.",
        5,
      ),
      q(
        "Çıkarım",
        "Nemli toprak örneği hangi düşünceyi destekler?",
        [
          "İlk çözümü uygulamadan önce durumu kontrol etmek gerekir.",
          "Sarkan yaprak her zaman susuzluktur.",
          "Bitkiler taşınmamalıdır.",
          "Tek bir gözlem bütün nedenleri açıklar.",
        ],
        0,
        "İlk su varsayımı dokunarak kontrol ediliyor ve kesin tanıdan kaçınılıyor.",
        3,
      ),
      q(
        "Bağlam",
        "“İlişkileri anlaşılmış bir yer” ne demektir?",
        [
          "Her bilimsel nedeni bilinen yer",
          "Koşulları ve kullanım kararları tanınan yer",
          "Tamamen değiştirilmiş yer",
          "Yalnızca adı konmuş bitkiler",
        ],
        1,
        "Mina zaman, yer, amaç ve davranış ilişkilerini öğrenmiştir.",
        6,
      ),
    ],
    summary:
      "Mina bahçesini büyük bir planla değil, saatlere ve kullanıma göre gözleyerek düzenler. İlk neden yorumlarını sınar; olumlu durumları da kaydeder ve geçici ihtiyacı kalıcı kurala çevirmeden çözer.",
    points: [
      "İyi yer amaca ve saate bağlıydı.",
      "Tek belirti tek nedeni kanıtlamadı.",
      "Olumlu gözlemler korunacak işleri gösterdi.",
      "Seyrek ihtiyaç günlük düzeni belirlemedi.",
      "Gelişim görüntüden çok kullanım bilgisindeydi.",
    ],
    scan: {
      prompt: "Kalabalık buluşmaların ne sıklıkla olması planlanıyordu?",
      answer: "Ayda bir",
      paragraph: 5,
    },
  },
  {
    id: "r39",
    title: "Kayıp günün arşivi",
    genre: "Anlatı",
    level: 3,
    complexity:
      "Birden çok belge, farklı anlatıcı bilgisi ve belirsiz çıkarımlar.",
    role: "practice",
    paragraphs: [
      `Küçük kasabanın fotoğraf atölyesi kapanırken, arka odada üzerinde tarih bulunmayan bir zarf çıktı. İçinde aynı meydana ait beş fotoğraf vardı. Birinde boş sandalyeler, birinde yarısı sökülmüş bir sahne, diğerinde yağmurdan ıslanmış bir afiş görünüyordu. Atölyeyi devralan Ada, fotoğrafların bir şenlik sonrasına ait olduğunu düşündü. Zarfın üzerine “Şenlik bitimi” yazmaya hazırlanırken, masanın çekmecesinde aynı meydanı gösteren bir kartpostal buldu. Kartpostaldaki sahne fotoğraftakine benziyor, ama arkasındaki bina farklı görünüyordu. Ada kalemi bıraktı. Birbirine benzeyen görüntüler aynı güne ait olmayabilirdi. Arşive ilk işi olarak yaptığı şeyi, yalnızca zarf düzenlemek sanmıştı; şimdi aslında bir yorum kaydetmek üzere olduğunu fark ediyordu.`,
      `Atölyenin eski sahibi Cemil ertesi gün geldi. Fotoğraflara bakınca yağmurlu bir yaz akşamını hatırladığını söyledi. Meydanda yapılacak gösteri son anda kapalı salona taşınmıştı. Ada bu bilgiyi hemen zarfın üstüne yazmak istedi. Cemil ise hangi yıl olduğunu hatırlamadığını, belki de başka bir etkinliği düşündüğünü ekledi. Anısında insanların sandalyeleri taşıdığı canlı bir sahne vardı, fakat fotoğraftaki afişin renginden emin değildi. Ada notunu iki parçaya ayırdı: fotoğrafta görülenler ve Cemil'in hatırladıkları. Bu ayrım anlatıyı daha az akıcı kılıyor gibi görünüyordu, ama bir gözlemi kesin tarihsel bilgiye dönüştürmesini önlüyordu. Belgelerle anılar birbirini tamamlayabilir, yine de aynı türden dayanak sayılmazdı.`,
      `Ada arka raftaki eski duyuruları taradı. Bir kâğıtta yaz gösterisinin yağmur nedeniyle ertelendiği yazıyordu. Başka bir duyuruda etkinliğin kapalı salona alındığı belirtilmişti. İkisinde farklı tarihler vardı. Fotoğraflardaki afişin okunabilen köşesinde yalnızca “akşam” sözcüğü seçiliyordu; gün ve ay yırtılmıştı. İlk bulduğu duyuruyu doğru kabul etmek kolaydı, fakat aynı tür etkinliğin birkaç kez yapılmış olması mümkündü. Ada aradığı şeyin yalnızca bir benzerlik değil, fotoğrafları belirli bir güne bağlayan ayırt edici bir bilgi olduğunu anladı. Sahnenin biçimi, sandalyelerin rengi ve meydanın adı pek çok günde aynı olabilirdi. Gerekli olan, diğer olasılıkları daraltacak bir ayrıntıydı.`,
      `Üçüncü fotoğrafı büyüteçle incelerken sahnenin yanında küçük bir tahta levha gördü. Üzerinde yarım kalmış bir sayı vardı. Atölyedeki takvim notlarında o sayıyla biten bir sergi hazırlığı geçiyordu. Ada heyecanlandı; sonunda eşleşmeyi bulduğunu düşündü. Ancak levhanın bir tarih değil, taşınacak sandıkların numarası olabileceğini de fark etti. Kendi beklentisi ayrıntıya anlam yüklüyordu. Notuna iki olasılığı da yazdı. Bu noktada çalışma yavaşlamıştı. Yine de yavaşlama boşa zaman geçirmek değildi; yanlış bir kesinliğin dosyalara yerleşmesini engelliyordu. Bir kez doğru kabul edilen başlık, sonraki kişilerin başka açıklamalar aramasını güçleştirebilirdi. Arşivde küçük bir etiket, gelecekte uzun bir anlatının temeli olabilirdi.`,
      `Birkaç gün sonra meydana yakın dükkânda çalışan Sevim fotoğrafları gördü. Afişi değil, arkadaki pencerede duran kumaşı tanıdı. Dükkânın içi yenilenirken o pencerenin iki hafta boyunca örtülü kaldığını hatırlıyordu. Ada bunun kesin bir gün vermediğini, ama olasılık aralığını daralttığını düşündü. Eski sipariş defterindeki tadilat kaydı aynı dönemi işaret ediyordu. İki ayrı bilgi birbirini destekliyordu; yine de fotoğrafların beşinin de aynı gün çekildiği henüz gösterilmiş değildi. Zarfın bir arada bulunması, içeriklerin bir arada üretildiği anlamına gelmeyebilirdi. Ada her fotoğraf için ayrı bir küçük kayıt açtı. Düzeni biraz uzatan bu adım, birbirinden farklı kanıtları tek hikâyede eritmesini önledi.`,
      `Atölyenin açılışı yaklaşırken Ada'dan giriş duvarına kısa bir geçmiş panosu hazırlaması istendi. Her ayrıntıyı çözmek için zamanı yoktu. Bildiklerini ve bilmediklerini ayırarak yazdı: Fotoğraflar yaz etkinlikleri dönemindeki meydanı gösteriyordu; bazılarının yağmur sonrası hazırlıklarla ilişkili olması mümkündü; kesin gün henüz belirlenmemişti. Cemil ilk metni biraz kuru buldu. Kendi hatırladığı sandalyeleri taşıyan kalabalık daha canlıydı. Ada onun anısını ayrı bir kutuda, sahibini belirterek ekledi. Böylece pano yalnızca ihtiyatlı bir listeye dönüşmedi; insan sesi korunurken belgenin göstermediği şey kesin gerçek gibi sunulmadı. Okuyucu hem görüntüye hem hatıraya bakabilecek, aralarındaki farkı görebilecekti.`,
      `Açılış günü bir ziyaretçi panoyu uzun süre inceledi. Fotoğraflardan birindeki çocuğun kendisi olabileceğini söyledi, fakat yüz net değildi. Ada hemen adını fotoğrafa yazmadı. Ziyaretçinin iletişim bilgisini izin alarak ayrı bir notta tuttu ve evindeki fotoğraflarla karşılaştırmasını önerdi. Bu karşılaşma arşivin bitmiş bir hikâye olmadığını gösteriyordu. Yeni bilgi gelebilir, eski yorum değişebilirdi. Bunun için her şeyi belirsiz bırakmak da gerekmiyordu. Görünen sandalyeler, sökülen sahne ve ıslak afiş güvenle tarif edilebiliyordu. Kesin olmayan, bunların hangi olay dizisinin parçası olduğuydu. Ada artık bilmek ile hiç bilmemek arasında birçok açıklık düzeyi bulunduğunu daha iyi anlıyordu.`,
      `Ay sonunda zarfın üstünde ilk düşündüğü başlık yoktu. Onun yerine “Meydan: yaz etkinliklerine ait tarihsiz fotoğraflar” yazıyordu. İçinde her fotoğrafın gözlemleri, olası bağlantıları ve bu bağlantıların dayanakları bulunuyordu. Ada kayıp günü tam olarak bulamamıştı. Buna rağmen işi başarısız saymadı; yanlış bir günü kesinleştirmemiş, gelecekte araştıracak kişiye düzenli bir başlangıç bırakmıştı. Arşiv, kusursuz bir hikâye elde etmek için boşlukları doldurmak değildi. Parçaların hangi ilişkiyi desteklediğini ve hangisinin henüz kurulamadığını korumaktı. Fotoğraflar eskisi kadar sessiz görünmüyordu. Her biri bir şey söylüyor, fakat hiçbirinin söylemediği cümleyi onların yerine kurmak gerekmiyordu. Ada'nın asıl öğrendiği, dikkatli okumanın bazen iyi bir soruyla durabilmek olduğuydu.`,
    ],
    questions: [
      q(
        "Ana düşünce",
        "Ada’nın çalışmasının temel kazanımı nedir?",
        [
          "Kesin bir tarih bulması",
          "Bütün anıları geçersiz sayması",
          "Görsel, anı ve yorumu dayanaklarıyla ayırması",
          "Fotoğrafları tek öyküye zorlaması",
        ],
        2,
        "Son paragraf kurulan ve kurulamayan ilişkileri korumayı başarı olarak tanımlar.",
        7,
      ),
      q(
        "Açık bilgi",
        "Sevim hangi ayrıntıyı tanıdı?",
        [
          "Sahnedeki sayıyı",
          "Penceredeki kumaşı",
          "Çocuğun yüzünü",
          "Sandalyenin markasını",
        ],
        1,
        "Tadilat sırasında pencerenin örtülü kaldığını hatırlıyor.",
        4,
      ),
      q(
        "İlişki",
        "Her fotoğraf için neden ayrı kayıt açıldı?",
        [
          "Zarflar yetersiz olduğu için",
          "Fotoğraflar hiç görünmediği için",
          "Pano büyük olduğu için",
          "Aynı zarfta olmanın aynı gün demek olmaması nedeniyle",
        ],
        3,
        "Birlikte saklanma ile birlikte üretilme ayrılıyor.",
        4,
      ),
      q(
        "Çıkarım",
        "Tahta levha örneği neyi gösterir?",
        [
          "Beklenti, belirsiz bir ayrıntının yorumunu etkileyebilir.",
          "Her sayı tarihtir.",
          "Fotoğraf büyütmek her sorunu çözer.",
          "Takvim kaydı her zaman yanlıştır.",
        ],
        0,
        "Ada sayıyı önce aradığı tarih gibi görüyor, sonra sandık numarası olasılığını düşünüyor.",
        3,
      ),
      q(
        "Bağlam",
        "“İyi bir soruyla durabilmek” ne anlama gelir?",
        [
          "İncelemeyi önemsiz saymak",
          "Yeterli dayanak yokken kesin sonuç uydurmamak",
          "Hiçbir bilgi kaydetmemek",
          "Yalnızca anılara inanmak",
        ],
        1,
        "Sonuç belirsizliği koruyor ama düzenli dayanaklar bırakıyor.",
        7,
      ),
    ],
    summary:
      "Ada tarihsiz fotoğrafları incelerken gördüklerini, anıları ve yorumları ayırır. Birkaç ipucu zaman aralığını daraltır, kesin gün vermez. Sonuç, uydurulmuş tamamlanmış hikâye yerine dayanakları açık bir arşivdir.",
    points: [
      "Benzerlik tek başına aynı günü göstermedi.",
      "Anı ile fotoğraf gözlemi ayrı kaydedildi.",
      "Sayı için alternatif açıklama korundu.",
      "Aynı zarf aynı üretim günü demek değildi.",
      "Kesinleşmeyen tarih dürüstçe açık bırakıldı.",
    ],
    scan: {
      prompt: "Cemil’in anısı panoda nasıl yer aldı?",
      answer: "Sahibi belirtilen ayrı bir kutuda",
      paragraph: 5,
    },
  },
  {
    id: "r40",
    title: "Bir metinle çalışmanın bütün günü",
    genre: "Öğretici",
    level: 3,
    complexity: "Birden çok stratejiyi koşula göre bütünleştirme ve aktarım.",
    role: "practice",
    paragraphs: [
      `Bir metni iyi okumak, başından sonuna aynı hızla ilerlemekten daha geniş bir iştir. Bunu görmek için Elvan'ın sıradan bir çalışma gününü izleyelim. Sabah masasına oturduğunda önünde bir toplantı notu, uzun bir inceleme yazısı ve akşam okuyacağı bir öykü vardı. Üçü de sözcüklerden oluşuyordu, fakat aynı okuma davranışını istemiyordu. Toplantı notunda kendisine düşen işi ve son tarihi bulacaktı. İnceleme yazısında bir önerinin hangi gerekçelerle savunulduğunu anlaması gerekiyordu. Öyküyü ise yalnızca olayın sonunu öğrenmek için değil, anlatının içinde zaman geçirmek için okuyacaktı. İlk kararı hız değildi: Her metnin sonunda ne yapabilmek istediğini belirledi.`,
      `Toplantı notunu açınca bütün satırları sırayla okumadı. Önce adını, görev bildiren ifadeleri ve tarihleri aradı. Bir satırda kendi adı geçti, fakat bu satır tamamlanmış bir işe teşekkür ediyordu. Adını bulmak tek başına yeterli değildi. Bir sonraki bölümde “Elvan, taslağı perşembeye kadar paylaşacak” cümlesini gördü. Cümlenin çevresini okuyup taslağın kapsamını kontrol etti. Sonra görevi takvimine kaydetti. Burada bütün notu derinlemesine okuduğunu söylemezdi. Belirli bilgiyi aramış, bulduğunu bağlamıyla doğrulamıştı. Taranan sayfanın kelime sayısını geçen zamana bölerek yüksek bir okuma hızı çıkarmak bu davranışı yanlış adlandırmak olurdu. Başarı, doğru işi ve doğru sınırı bulmaktı.`,
      `İnceleme yazısında farklı bir başlangıç yaptı. Başlığı, ara başlıkları ve son paragrafı gözden geçirdi. Yazarın ortak çalışma alanları hakkında bir öneri sunduğunu gördü. Kendi sorusunu yazdı: Bu öneri hangi koşullarda işe yarayabilir? Sonra girişten başlayarak doğal ritmiyle okudu. İlk birkaç paragraf tanıdık örnekler taşıdığı için rahat ilerledi. Daha sonra maliyet ile erişim arasında bir karşılaştırma geldi. Elvan burada yavaşladı. Karşılaştırılan iki seçeneğin hangi ölçütle değerlendirildiğini anlamadan devam ederse sonraki sonucu da yanlış okuyabilirdi. Yavaşlama bir gerileme değildi; metnin daha fazla ilişki kurmayı istediği yerde okuma davranışını değiştirmekti.`,
      `Bir paragrafın sonunda Elvan, yazarın önceki öneriyi desteklediğini düşündü. Sonraki cümlede geçen “buna karşılık” ifadesi bu yorumu sarstı. Geri dönüp baktığında bir koşulu atladığını gördü: Öneri yalnızca düzenli bakım sağlanırsa işe yarayacaktı. Paragrafı baştan sona birkaç kez tekrarlamak yerine koşul cümlesini ve sonucu birlikte okudu. Kenara “yarar bakım düzenine bağlı” diye yazdı. Bu kısa not, metnin bütün sözcüklerini saklamıyordu. Önemli ilişkiyi koruyordu. Elvan her geri dönüşü kötü bir alışkanlık saymış olsaydı anlamı bozuk biçimde sürdürebilirdi. Amaçlı yeniden okuma, akıcılığın düşmanı değil, anlamın yeniden kurulmasına yarayan bir araç olmuştu.`,
      `Yirmi dakika sonra dikkatinin metinden uzaklaştığını fark etti. Gözleri satırları geçiyor, fakat son iki paragrafın işini söyleyemiyordu. Sayfayı kapatmadan önce son anladığı noktaya kısa bir işaret bıraktı ve ayağa kalktı. Molada başka bir uzun yazı açmadı. Döndüğünde önce işaretin yanındaki notu okudu, sonra kopuşun başladığı paragraftan devam etti. Kaydırmanın ilerlemiş olmasını okuma tamamlanması saymıyordu. Elvan'ın kendine verdiği bilgi basitti: Bu bölümde bulunmuştum, ama anlamını kurduğumdan emin değildim. Böyle bir öz bildirim kusursuz ölçüm değildir; yine de hiç sorgulamadan tamamlandı demekten daha yararlı bir öğrenme kararı sağlayabilir.`,
      `Yazıyı bitirdiğinde hemen metne bakarak güzel bir özet çıkarmadı. Önce ekranı kapatıp ana savı, iki gerekçeyi ve bir sınırı kendi cümleleriyle yazdı. Gerekçelerden biri eksikti. Metne döndüğünde eksik bağlantıyı buldu ve ilk notunu farklı bir işaretle tamamladı. Böylece ilk denemede neyi hatırladığı ile metne bakarak ne eklediği ayrılmış oldu. Ertesi gün aynı sorulara yeniden yanıt verecekti. Hatırlama çalışmasının amacı kendini yakalamak değil, hangi bilginin tekrar gerektirdiğini görmekti. Anahtar sözcüklerin birkaçını yazmış olması otomatik olarak güçlü anlama anlamına gelmezdi; onların arasındaki ilişkinin de kendi anlatısında bulunup bulunmadığını kontrol etmesi gerekiyordu.`,
      `Akşam öyküyü açtığında sabahki bilgi tarama yaklaşımını kullanmadı. Bir karakterin adını bulup olay sonuna atlamak, o anki amacına hizmet etmeyecekti. Diyalogların ritmine, anlatıcının bazı ayrıntıları söylemeyişine ve önceki sahnenin sonraki sahnede nasıl yankılandığına dikkat etti. Bazen bir cümlede durdu; bunun hız kaybı diye kaydedilmesi gerekmiyordu. Bir arkadaşına öyküden söz ederken yalnızca “ne oldu”yu değil, bir davranışın neden kendisini düşündürdüğünü anlatmak istedi. Bu okumanın başarısı başka bir ölçütteydi. Metnin türü de tek başına karar vermiyordu: Aynı öyküyü bir karakterin geçtiği sayfayı bulmak için açsaydı tarama yapabilirdi. Tür kadar amaç da belirleyiciydi.`,
      `Günün sonunda Elvan üç metni üç ayrı biçimde kullanmıştı. Toplantı notunda bilgi bulmuş, inceleme yazısında savları ilişkilendirmiş, öyküde anlatının deneyimine yer vermişti. Bunları tek bir hız sayısında toplamak yararlı olmayacaktı. Ortak beceri, her durumda daha hızlı hareket etmek değil, ne yaptığını bilerek okuyabilmekti. Bir sonraki hafta kendisine küçük bir çalışma düzeni kurdu: yeni bir bilgilendirici metinde yardımsız okuma, ertesi gün kısa geri çağırma ve keyif için serbest bir uzun okuma. Plan yoğun günlerde kısalabilir, ara verildiğinde yeniden başlayabilirdi. Kursların ve alıştırmaların gerçek karşılığı burada ortaya çıkıyordu: araç olmadan, tanımadığı bir metinde, kendi sorusuna uygun yolu seçebilmek ve gerektiğinde o yolu değiştirebilmek.`,
    ],
    questions: [
      q(
        "Ana düşünce",
        "Günün üç okumasını birleştiren beceri nedir?",
        [
          "Her metni aynı sürede bitirmek",
          "Bütün metinleri ezberlemek",
          "Daima geri dönüşsüz okumak",
          "Amaca göre strateji seçip anlamı izlemek",
        ],
        3,
        "Son paragraf ortak beceriyi bilinçli seçim olarak tanımlar.",
        7,
      ),
      q(
        "Açık bilgi",
        "Elvan taslağı ne zamana kadar paylaşacak?",
        ["Perşembeye kadar", "Pazartesi sabahı", "Cuma akşamı", "Ay sonunda"],
        0,
        "Görev cümlesi ikinci paragraftadır.",
        1,
      ),
      q(
        "İlişki",
        "“Buna karşılık” ifadesi neyi tetikledi?",
        [
          "Öyküye geçmeyi",
          "Atlanan koşulu bulmak için hedefli geri dönüşü",
          "Metni bırakmayı",
          "Bütün notları silmeyi",
        ],
        1,
        "İfade yorumunu sarsınca bakım koşuluna döner.",
        3,
      ),
      q(
        "Çıkarım",
        "Aynı öykü farklı amaçla nasıl okunabilir?",
        [
          "Mutlaka aynı biçimde",
          "Yalnızca seri sunumla",
          "Belirli sayfayı bulmak için taranarak",
          "Önce bütün soruları ezberleyerek",
        ],
        2,
        "Yedinci paragraf karakterin sayfasını bulma örneği verir.",
        6,
      ),
      q(
        "Bağlam",
        "İlk not ile sonradan eklenen not neden ayrılıyor?",
        [
          "Daha renkli görünmek için",
          "Metni uzun tutmak için",
          "Okuma hızını yükseltmek için",
          "Yardımsız hatırlama ile metne bakmayı ayırmak için",
        ],
        3,
        "İlk geri çağırma ve kaynakla tamamlama farklı davranışlardır.",
        5,
      ),
    ],
    summary:
      "Elvan metinleri amaçlarına göre tarar, ilişkilendirerek okur ve anlatı deneyimine zaman ayırır. Anlam kopunca hedefli döner, mola verir ve hatırlamayı metin kapalıyken dener. Ortak başarı tek hız değil bilinçli strateji seçimidir.",
    points: [
      "Taramada hedef bilgi bağlamıyla doğrulandı.",
      "Zor ilişkide yavaşlandı.",
      "Koşula hedefli geri dönüş yapıldı.",
      "Metin kapalı geri çağırma ayrı kaydedildi.",
      "Amaç değişirse aynı metinde strateji de değişebilir.",
    ],
    scan: {
      prompt: "Elvan özetinde hangi dört öğeyi yazmayı denedi?",
      answer: "Ana sav, iki gerekçe ve bir sınır",
      paragraph: 5,
    },
  },
];
